/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardDisplay: typeof import('./components/CardDisplay.vue')['default']
    CardsListWithMetadata: typeof import('./components/CardsListWithMetadata.vue')['default']
    CollectorNumberSelector: typeof import('./components/CollectorNumberSelector.vue')['default']
    DownloadCardsList: typeof import('./components/DownloadCardsList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LangSelector: typeof import('./components/LangSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetCodeSelector: typeof import('./components/SetCodeSelector.vue')['default']
  }
}
